default:
  tags:
    - docker


workflow:
  rules:
    - when: always
      if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
    - when: never


stages:
  - build



build:pquery:
  stage: build
  image: "ubuntu:24.04"
  before_script:
    - apt update && apt install -y make cmake lsb-release build-essential devscripts libssl-dev libmysqlclient-dev default-libmysqlclient-dev
  script:
    - cmake .
    - cpack
    - ls -la
  # artifacts:
