CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(PQuery)
#
SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)
#
SET(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
OPTION(DEVELOPER_MODE "Enable developer mode" OFF)
OPTION(BUILD_DOCS "Generate docs with Doxygen" OFF)
OPTION(WITH_MYSQL "Build with MySQL support" ON)
OPTION(WITH_PGSQL "Build with PostgreSQL support" OFF)
#
INCLUDE(PQDoxygen)
INCLUDE(PQSetupCompiler)
INCLUDE(PQDatabases)
INCLUDE(PQVersion)
INCLUDE(PQCPack)
#
ADD_SUBDIRECTORY(src)
#
