#
# Packaging for Windows is not implemented
IF(NOT UNIX)
  RETURN()
ENDIF()
#
INCLUDE(InstallRequiredSystemLibraries)
#
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PQuery is an open-source multi-threaded test program to stress test the MySQL/PgSQL server")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
SET(CPACK_PACKAGE_NAME pquery3)
SET(CPACK_PACKAGE_CONTACT "abychko@gmail.com")
SET(CPACK_PACKAGE_VENDOR "ABYCHKO.EXPERT")
SET(CPACK_PACKAGE_VERSION_MAJOR ${vMajor})
SET(CPACK_PACKAGE_VERSION_MINOR ${vMinor})
SET(CPACK_PACKAGE_VERSION_PATCH ${vPatch})
SET(CPACK_PACKAGE_VERSION_RELEASE ${vExtra})
SET(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
SET(CPACK_SOURCE_STRIP_FILES ON)
#
SET(CPACK_GENERATOR "TGZ;STGZ")
#
IF(BUILD_RPM)
  IF(EXISTS "/usr/bin/rpmbuild")
    SET(CPACK_GENERATOR "${CPACK_GENERATOR};RPM")
  ENDIF()
ENDIF()
#
IF(BUILD_DEB)
  IF(NOT EXISTS "/usr/bin/dpkg")
    MESSAGE(FATAL_ERROR "Not Debian-based platform, but .deb build is requested")
  ENDIF()
  SET(CPACK_GENERATOR "${CPACK_GENERATOR};DEB")
  SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alexey Bychko")
  IF(NOT EXISTS "/usr/bin/lsb_release")
    MESSAGE(WARNING "lsb_release is not installed, CODENAME is set to UNKNOWN")
    SET(CODENAME "UNKNOWN")
  ELSE()
    EXECUTE_PROCESS(COMMAND lsb_release -sc
      WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
      RESULT_VARIABLE res OUTPUT_VARIABLE CODENAME
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    IF(NOT res EQUAL 0)
      SET(CODENAME "UNKNOWN")
    ENDIF()
  ENDIF()
  IF(ARCH MATCHES "x86_64")
    SET(ARCH "amd64")
  ENDIF()
  SET(CPACK_PACKAGE_VERSION_RELEASE ${vExtra}.${CODENAME})
  SET(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CPACK_PACKAGE_VERSION_RELEASE}_${ARCH}")
ELSE()
  SET(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${CPACK_PACKAGE_VERSION_RELEASE}.${CMAKE_SYSTEM_NAME}.${ARCH}")
ENDIF()















#


#
MESSAGE("==> CPACK will produce: ${CPACK_GENERATOR}")
#
INCLUDE(CPack)
#
